In [3]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [15]:
# Create a 1-dimensional NumPy array using np.array()
one_d = np.array([3,5,7])
# Create a 2-dimensional NumPy array using np.array()
two_d = np.array([[3,5,7], [3,5,7]])
# Create a 3-dimensional Numpy array using np.array()
# three_d = np.array([3,5,7],[3,5,7],[3,5,7])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [15]:
def printArr(arr):
    print(arr.shape, arr.dtype, arr.size)

In [16]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
printArr(one_d)

(3, 3, 1) float64 9


In [17]:
# Attributes of 2-dimensional array
printArr(two_d)

(3, 3, 2) float64 18


In [18]:
# Attributes of 3-dimensional array
printArr(three_d)

(3, 3, 3) float64 27


In [19]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

pd.DataFrame(two_d, index=["First row", "Second row"], columns=["First col", "Sec col", "Third col"])

First col  Sec col  Third col
First row           3        5          7
Second row          3        5          7

In [22]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
# Create an array of shape (7, 2, 3) of only zeros
three_d = np.zeros((7,2,3))
three_d.shape

(7, 2, 3)

In [29]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [30]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0,10,(7,2))

array([[9, 5],
       [6, 7],
       [1, 6],
       [1, 6],
       [2, 6],
       [0, 7],
       [8, 3]])

In [35]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.uniform(size=(3,5))

array([[0.00706631, 0.02306243, 0.52477466, 0.39986097, 0.04666566],
       [0.97375552, 0.23277134, 0.09060643, 0.61838601, 0.38246199],
       [0.98323089, 0.46676289, 0.85994041, 0.68030754, 0.45049925]])

In [37]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10,(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [45]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

randoms = np.random.randint(1,10,(3,7))

# Find the unique numbers in the array you just created
np.unique(randoms)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
# Find the 0'th index of the latest array you created
randoms[0]

array([1, 4, 7, 2, 3, 1, 5])

In [57]:
# Get the first 2 values of the first 2 rows of the latest array
randoms[:2]

array([[1, 4, 7, 2, 3, 1, 5],
       [1, 8, 1, 1, 2, 2, 6]])

In [62]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
size = (3,5);
first_arr = np.random.randint(0,10,size)
sec_arr = np.ones(size)

In [69]:
# Add the two arrays together
sum_of_arr = first_arr + sec_arr
sum_of_arr
sum_of_arr.shape

(3, 5)

In [72]:
# Create another array of ones of shape (5, 3)
another = np.ones((5,3))

another = another.T
another.shape


(3, 5)

In [74]:
# Try add the array of ones and the other most recent array together
another_addition = sum_of_arr + another
another_addition

array([[ 9.,  5.,  2.,  9.,  5.],
       [ 7.,  9.,  5.,  4., 10.],
       [ 4., 10.,  3.,  3.,  3.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [76]:
# Create another array of ones of shape (3, 5)
yet_another = np.ones((3,5))

In [77]:
# Subtract the new array of ones from the other most recent array
yet_another - another_addition

array([[-8., -4., -1., -8., -4.],
       [-6., -8., -4., -3., -9.],
       [-3., -9., -2., -2., -2.]])

In [78]:
# Multiply the ones array with the latest array
yet_another * another_addition

array([[ 9.,  5.,  2.,  9.,  5.],
       [ 7.,  9.,  5.,  4., 10.],
       [ 4., 10.,  3.,  3.,  3.]])

In [79]:
# Take the latest array to the power of 2 using '**'
yet_another**2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [80]:
# Do the same thing with np.square()
np.square(yet_another)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [83]:
# Find the mean of the latest array using np.mean()
np.mean(another_addition)

5.866666666666666

In [84]:
# Find the maximum of the latest array using np.max()
np.max(another_addition)

10.0

In [86]:
# Find the minimum of the latest array using np.min()
np.min(another_addition)

2.0

In [87]:
# Find the standard deviation of the latest array
np.std(another_addition)

2.753583523741784

In [88]:
# Find the variance of the latest array
np.var(another_addition)

7.58222222222222

In [90]:
# Reshape the latest array to (3, 5, 1)
another_addition.reshape((3,5,1))

array([[[ 9.],
        [ 5.],
        [ 2.],
        [ 9.],
        [ 5.]],

       [[ 7.],
        [ 9.],
        [ 5.],
        [ 4.],
        [10.]],

       [[ 4.],
        [10.],
        [ 3.],
        [ 3.],
        [ 3.]]])

In [91]:
# Transpose the latest array
another_addition.T

array([[ 9.,  7.,  4.],
       [ 5.,  9., 10.],
       [ 2.,  5.,  3.],
       [ 9.,  4.,  3.],
       [ 5., 10.,  3.]])

What does the transpose do?

In [101]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
f = np.array([[3,2,1],[7,2,3]])
s = np.array([[1,2,8], [3,2,1]])

In [102]:
f

array([[3, 2, 1],
       [7, 2, 3]])

In [105]:
s = s.T
s

array([[1, 3],
       [2, 2],
       [8, 1]])

In [106]:
# Perform a dot product on the two newest arrays you created
np.dot(f,s)

array([[15, 14],
       [35, 28]])

In [108]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
f = np.random.randint(0,10,(4,3))
s = np.random.randint(0,10,(4,3)).T

In [109]:
# Perform a dot product on the two newest arrays you created
np.dot(f,s)

array([[34,  7,  2, 28],
       [40,  8,  6, 24],
       [22, 21,  6, 24],
       [52, 20, 15, 24]])

It doesn't work. How would you fix it?

In [36]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [37]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [111]:
# Compare the two arrays with '>'
f > s.T

array([[False, False, False],
       [False,  True, False],
       [ True,  True, False],
       [False, False,  True]])

What happens when you compare the arrays with `>`?

In [114]:
# Compare the two arrays with '>='
f
f >= s.T

array([[False, False, False],
       [False,  True, False],
       [ True,  True, False],
       [False, False,  True]])

In [115]:
# Find which elements of the first array are greater than 7
f > 7
f

array([[1, 4, 0],
       [0, 4, 2],
       [3, 2, 0],
       [0, 4, 5]])

In [41]:
# Which parts of each array are equal? (try using '==')


In [120]:
# Sort one of the arrays you just created in ascending order
np.random.seed(0)
f.sort()
f

array([[0, 1, 4],
       [0, 2, 4],
       [0, 2, 3],
       [0, 4, 5]])

In [124]:
# Sort the indexes of one of the arrays you just created
f.argmax()

11

In [125]:
# Find the index with the maximum value in one of the arrays you've created
f.argmin()

0

In [45]:
# Find the index with the minimum value in one of the arrays you've created


In [46]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created


In [47]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created


In [48]:
# Create an array of normally distributed random numbers


In [49]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.